name: winclip
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - matplotlib
  - seaborn
  - pandas
  - tqdm
  - pyyaml
  - jupyter
  - pip
  - pip:
    - open-clip-torch>=2.24.0
    - ftfy>=6.1.3
    - regex>=2023.10.3
    - timm>=0.9.0
    - opencv-python>=4.8.0
    - einops>=0.7.0
